### ISSUE TITLE
Registration of PathBridge meta model is missing

### ISSUE THREAD

**Issue by seiferma** [ReEng/sdm-commons#29]
I noticed that there is a meta model with namespace `http://www.storydriven.org/patterns/expressions/pathbridge` that resides in the `model` folder but is not properly registered in the `plugin.xml` file.

Not registering the meta model properly, can lead to issues such as failed OCL validations as discussed in [PALLADIO-436](https://jira.palladio-simulator.com/browse/PALLADIO-436).

I suggest registering the genmodel in the `plugin.xml` file.

**Comment by snowball77** [comment]
I agree. Do you want to do it yourself? Should I add you to the project?

**Comment by seiferma** [comment]
Sure, I can integrate it. Nevertheless, I created a pull request that includes the fix.
